### ISSUE TITLE
notice of fork (working on integrating bbswitch)

### ISSUE THREAD

**Issue by sudopluto** [MarechalLima/Solus-Optimus-Switch#3]
Hi,

Just letting you know I'm making a fork of this repo. In my fork, I am going to be making use of bbswitch to control turning on and off the gpu. This way nouveau can always be blacklisted, as even loading nouveau can cause instability on my system. I am making this fork for my eventual switch back to arch linux, but I believe that the work I'm going can be used in Solus because bbswitch is in the default repos. 

-Pranav

**Comment by MarechalLima** [comment]
Hey, no need of Nouveau now, it's using bbswitch
